# Copyright (c) 2026 北京航空航天大学
# SPDX-License-Identifier: Apache-2.0
# 以服务端 revision 为基线开始一次自动收敛并自动释放资源的采样。
uint8 OPERATION_FIRST=1
uint8 OPERATION_NEXT=2

builtin_interfaces/Time stamp
string source_id
uint64 sequence
uint8 operation
int32 expected_tag_id
uint32 window_size
string expected_service_instance_id
uint64 expected_window_revision
uint64 expected_extnav_revision
bool apply
---
bool accepted
string job_id
string service_instance_id
uint64 window_revision
string message
